server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null


logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    admin-secret-key: aXRjYXN0aXRoZWNvZGVzZWNyZXRrZXlmb3Jqd3Q=
    admin-ttl: 31536000000
    admin-token-name: token
    user-secret-key: aXRjYXN0aXRoZWNvZGVzZWNyZXRrZXlmb3Jqd3Q=
    user-ttl: 31536000000
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
knife4j:
  enable: true
  setting:
    language: zh_cn
  wechat:
      appid: ${sky.wechat.appid}
      secret: ${sky.wechat.secret}